# Apply Producers Fix

Apply the fixes made from the `fix_missed_producers.csv` to the `grammy_winners.csv` file

In [20]:
import pandas
import pathlib

In [21]:
TMP_DIR = pathlib.Path('.') / 'tmp'

In [22]:
df1 = pandas.read_csv('grammy_winners.csv')

In [23]:
df2 = pandas.read_csv(TMP_DIR / 'fix_missed_producers.csv')

In [24]:
year = 1958

In [55]:
section_to_change = df2[df2.year == year][['id', 'producers']]

In [57]:
section_to_change.head()

     id                                          producers
0  7201            Henry Mancini; Henry Mancini > arranger
1  7143                      Domenico Modugno > songwriter
2  7206  Sherwood Hall III > engineer; (Laurindo Almeid...
3  7210      Ted (Theodore) Keep; David Seville > engineer
4  7215                       Frank Sinatra > art director

In [56]:
for item in section_to_change.itertuples(name='Award'):
    df1.loc[item.Index, 'producers'] = item.producers

In [66]:
df1[df1.isin({'producers': ['Henry Mancini; Henry Mancini > arranger']}).producers == True]

,year,annual_edition,category,artist,producers,song_or_album,winner,url
0,2024,67,Best Boxed Or Special Limited Edition Package,"Nick Azinas & Mike Hicks, art directors (Alpha...",Henry Mancini; Henry Mancini > arranger,Half Living Things,False,https://www.grammy.com/awards/67th-annual-gram...