In [13]:
import pandas

In [14]:
df = pandas.read_csv('grammy_winners_v2.csv')

If the name of the award is for individual single artists, the coliumn `song_or_album` should not have their name but should be empty

In [15]:
df2 = df[df.category == 'Best New Artist']

In [16]:
for item in df2.itertuples():
    df2.loc[item.Index, 'artist'] = item.song_or_album
    df2.loc[item.Index, 'song_or_album'] = pandas.NA

In [17]:
df2.head()

,id,year,edition,category,artist,song_or_album,url,producers,winner
1584,23036,1965,8,Best New Artist,Tom Jones,<NA>,https://www.grammy.com/awards/8th-annual-gramm...,Tom Jones,True
1770,23042,1965,8,Best New Artist,Marilyn Maye,<NA>,https://www.grammy.com/awards/8th-annual-gramm...,NaN,False
1771,23041,1965,8,Best New Artist,Sonny And Cher,<NA>,https://www.grammy.com/awards/8th-annual-gramm...,NaN,False
1772,23040,1965,8,Best New Artist,Herman's Hermits,<NA>,https://www.grammy.com/awards/8th-annual-gramm...,NaN,False
1773,23039,1965,8,Best New Artist,Horst Jankowski,<NA>,https://www.grammy.com/awards/8th-annual-gramm...,NaN,False

In [18]:
for item in df2.itertuples():
    df.loc[item.Index, 'artist'] = item.artist
    df.loc[item.Index, 'song_or_album'] = item.song_or_album

Remove `,` from the artist names and use `>` to indicate the person's role

In [19]:
def clean_artist(value: str | None):
    if value is None:
        return value
    
    if isinstance(value, float):
        return value

    if ', artist' in value:
        value = value.replace(', artist', ' > artist')

    if ', conductor' in value:
        value = value.replace(', conductor', ' > conductor')

    if ', songwriter' in value:
        value = value.replace(', songwriter', ' > songwriter')

    if ', pianist' in value:
        value = value.replace(', pianist', ' > pianist')

    if ', composer' in value:
        value = value.replace(', composer', ' > composer')

    if ', arranger' in value:
        value = value.replace(', arranger', ' > arranger')

    if ', engineer/mixer' in value:
        value = value.replace(', engineer/mixer', ' > engineer/mixer')

    if ', producer' in value:
        value = value.replace(', producer', ' > producer')

    if ', composer & lyricist' in value:
        value = value.replace(', composer & lyricist',
                                ' > composer & lyricist')

    if ', lyricist' in value:
        value = value.replace(', lyricist', ' > lyricist')

    if ', principal vocalists' in value:
        value = value.replace(', principal vocalists',
                                ' > principal vocalists')

    if ', art directors' in value:
        value = value.replace(', art directors', ' > art directors')

    if ', album notes writers' in value:
        value = value.replace(', album notes writers',
                                ' > album notes writers')

    if ', engineers' in value:
        value = value.replace(', engineers', ' > engineers')

    if ', engineer' in value:
        value = value.replace(', engineer', ' > engineer')

    if ', mastering engineer' in value:
        value = value.replace(', mastering engineer',
                                ' > mastering engineer')

    if ', remixers' in value:
        value = value.replace(', remixers', ' > remixers')

    if ',  immersive' in value:
        value = value.replace(',  immersive', ' > immersive')

    if ', compilation producer' in value:
        value = value.replace(', compilation producer',
                                ' > compilation producer')

    if ',  restoration engineer' in value:
        value = value.replace(',  restoration engineer',
                                ' > restoration engineer')
        
    if ', soloist' in value:
        value = value.replace(', soloist', ' > soloist')

    if ', remixer' in value:
        value = value.replace(', remixer', ' > remixer')

    if ', immersive audio' in value:
        value = value.replace(', immersive audio', ' > immersive audio')

    if ', album notes writer' in value:
        value = value.replace(', album notes writer',
                                ' > album notes writer')
        
    if ', video producer' in value:
        value = value.replace(', video producer', ' > video producer')

    if ', video director' in value:
        value = value.replace(', video director', ' > video director')

    value = value.replace(',', ';')

    return value

In [20]:
df.artist = df.artist.apply(clean_artist)

In [21]:
df.producers = df.producers.apply(clean_artist)

Fix names with `; Jr.` which means `Junior` and should not be separated by a `;`

In [22]:
def fix_junior(value: str | None):
    if value is None:
        return value
    
    if isinstance(value, float):
        return value

    if '; Jr.' in value:
        value = value.replace('; Jr.', ' Jr.')

    return value

In [27]:
df = df.rename(columns={'edition': 'annual_edition'})

In [28]:
df.head()

,id,year,annual_edition,category,artist,song_or_album,url,producers,winner
0,7144,1958,1,Song Of The Year,Cy Coleman & Carolyn Leigh > songwriters (Fran...,Witchcraft (Single),https://www.grammy.com/awards/1st-annual-gramm...,NaN,False
1,7145,1958,1,Song Of The Year,Alan J. Lerner & Frederick Loewe > songwriters...,Gigi (Single),https://www.grammy.com/awards/1st-annual-gramm...,NaN,False
2,7146,1958,1,Song Of The Year,Eddie Cooley & Johnny Davenport > songwriters ...,Fever,https://www.grammy.com/awards/1st-annual-gramm...,NaN,False
3,7147,1958,1,Song Of The Year,Lee Pockriss & Paul Vance > songwriters (Perry...,Catch A Falling Star,https://www.grammy.com/awards/1st-annual-gramm...,NaN,False
4,7148,1958,1,"Best Vocal Performance, Female",Ella Fitzgerald,Ella Fitzgerald Sings The Irving Berlin Song Book,https://www.grammy.com/awards/1st-annual-gramm...,NaN,True

In [29]:
df = df[['year', 'annual_edition', 'category', 'artist', 'song_or_album', 'url', 'producers', 'winner']]

In [30]:
df.to_csv('grammy_winners_v3.csv', index=False)